-- Create the alerts table
create table if not exists alerts (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()),
    type text not null,
    image_url text,
    status text default 'new',
    location jsonb
);

-- Enable real-time updates for the alerts table
alter publication supabase_realtime add table alerts;

-- Add indexes for better query performance
create index if not exists alerts_created_at_idx on alerts(created_at desc);
create index if not exists alerts_type_idx on alerts(type);
create index if not exists alerts_status_idx on alerts(status);

-- Configure Row Level Security (RLS)
alter table alerts enable row level security;

-- Create policies for the alerts table
create policy "Allow anonymous insert"
on alerts for insert
to anon
with check (true);

create policy "Allow anonymous select"
on alerts for select
to anon
using (true);

create policy "Allow anonymous update"
on alerts for update
to anon
using (true);

-- Note: Run these commands in the Supabase Dashboard:
-- 1. Go to Storage > Policies
-- 2. Click on the "wildguard" bucket
-- 3. Add these policies:
--    - For "SELECT" operations (downloading/viewing files):
--      CREATE POLICY "Give anonymous users access to files"
--      ON storage.objects FOR SELECT TO anon USING (true);
--    
--    - For "INSERT" operations (uploading files):
--      CREATE POLICY "Give anonymous users upload access"
--      ON storage.objects FOR INSERT TO anon WITH CHECK (true);